[tool.poetry]
name = "booz-allen-public-license-python"
version = "1.2.2.dev"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.group.dev.dependencies]
behave = "^1.2.6"
black = ">=24.3.0"
pylint = "^3.3.1"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core >= 1.6.0"]
build-backend = "poetry.core.masonry.api"
