# This workflow kicks off the releases a new version of booz-allen-licenses and deploys artifacts to Maven Central.

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Booz Allen Licenses

on:
    workflow_dispatch:
        inputs:
            releaseVersion:
                description: "Release version"
                required: true
            developmentVersion:
                description: "Next development version"
                required: true

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Install Python # use direct install rather than pyenv for CI for large speed improvement
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11.4'
            - name: Install Poetry
              uses: snok/install-poetry@v1
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                  java-version: '11'
                  distribution: 'temurin'
                  server-id: 'ossrh'
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
                  gpg-passphrase: GPG_PASSPHRASE
            - name: Release Booz Allen Licenses
              run: |
                  git config --local user.email "aissemble-noreply@bah.com"
                  git config --local user.name "Github Actions"
                  git checkout -b $1-release
                  mvn -B release:clean release:prepare release:perform -DreleaseVersion=$1 -DdevelopmentVersion=$2
                  mvn versions:set -DnewVersion=$2 -DgenerateBackupPoms=false
                  mvn clean install
                  mvn scm:checkin -Dmessage=":arrow_up: push example modules to version $2"
              env:
                  MAVEN_USERNAME: ${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_USER }}
                  MAVEN_PASSWORD: ${{ secrets.SONATYPE_CENTRAL_REPO_TOKEN_KEY }}
                  GPG_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
